---

- name: Verify required variables are defined
  ansible.builtin.assert:
    that:
    - lookup('vars', item) is defined
    - lookup('vars', item) | length > 0
    fail_msg: "Required variable '{{ item }}' is not defined or empty."
  loop:
  - act_runner_gitea_url
  - act_runner_token
